- name: Create new resources
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Create the keypair
      os_keypair:
        state: present
        name: "{{ prefix }}-key"
        public_key_file: "./{{ prefix }}.key.pub"
    - name: Create security groups
      os_security_group:
        state: present
        name: "{{ prefix }}-rules-minion"
    # the following rules are defined according to https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#check-required-ports
    - name: Add rules to minions
      os_security_group_rule:
        state: present
        security_group: "{{ prefix }}-rules-minion"
        direction: ingress
        ethertype: IPv4
        protocol: tcp
        remote_ip_prefix: 0.0.0.0/0
        port_range_min: "{{ item.min }}"
        port_range_max: "{{ item.max }}"
      with_items:
        - { min: 10250, max: 10250 }
        - { min: 30000, max: 32767 }
