- name: Remove instances
  hosts: comp-sci-7412-group-*-*
  gather_facts: no
  connection: local
  strategy: free
  tasks:
    - name: Remove instance
      os_server:
        state: absent
        name: "{{ inventory_hostname }}"
