version: 1
update_configs:
  - package_manager: javascript
    directory: web
    update_schedule: daily
    target_branch: dev/web
    default_assignees:
      - laitingsheng
    default_reviewers:
      - laitingsheng
    default_labels:
      - dependabot
      - enhancement
  - package_manager: java:gradle
    directory: backend
    update_schedule: daily
    target_branch: dev/backend
    default_assignees:
      - laitingsheng
    default_reviewers:
      - laitingsheng
    default_labels:
      - dependabot
      - enhancement
  - package_manager: docker
    directory: backend
    update_schedule: daily
    target_branch: dev/backend
    default_assignees:
      - laitingsheng
    default_reviewers:
      - laitingsheng
    default_labels:
      - dependabot
      - enhancement
