version: 1
update_configs:
  - package_manager: javascript
    update_schedule: daily
    default_assignees:
      - laitingsheng
    default_reviewers:
      - laitingsheng
    default_labels:
      - dependabot
      - enhancement
  - package_manager: docker
    update_schedule: daily
    default_assignees:
      - laitingsheng
    default_reviewers:
      - laitingsheng
    default_labels:
      - dependabot
      - enhancement
