- name: Destroy resources
  hosts: "{{ prefix }}-*-*"
  gather_facts: no
  connection: local
  strategy: free
  tasks:
    - name: Remove instance
      os_server:
        state: absent
        name: "{{ inventory_hostname }}"
    - name: Remove the keypair
      os_keypair:
        state: absent
        name: "{{ prefix }}-key"
    - name: Remove security groups
      os_security_group:
        state: absent
        name: "{{ prefix }}-rules-{{ item }}"
      with_items:
        - master
        - minion
